<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("");?>
<?
$APPLICATION->IncludeComponent(
	"bitrix:desktop", 
	".default", 
	array(
		"ID" => "mainpage",
		"CAN_EDIT" => "N",
		"COLUMNS" => "1",
		"COLUMN_WIDTH_0" => "100%",
		"G_ADV_TYPE" => "INFO",
		"GADGETS" => array(
			0 => "HELLO",
		),
		"G_VIDEO_IBLOCK_TYPE" => "services",
		"G_VIDEO_IBLOCK_ID" => "10",
		"G_VIDEO_PATH_TO_FILE" => "22",
		"G_VIDEO_DURATION" => "22",
		"G_VIDEO_SECTION_ID" => "",
		"G_VIDEO_ELEMENT_ID" => "47",
		"G_VIDEO_WIDTH" => "400",
		"G_VIDEO_HEIGHT" => "300",
		"G_VIDEO_CACHE_TYPE" => "A",
		"G_VIDEO_LIST_URL" => "/about/media.php",
		"G_VIDEO_CACHE_TIME" => "3600",
		"G_VOTE_CHANNEL_SID" => "COMPANY_s1",
		"G_VOTE_CACHE_TYPE" => "A",
		"G_VOTE_CACHE_TIME" => "3600",
		"G_VOTE_LIST_URL" => "/services/votes.php",
		"G_BIRTHDAY_STRUCTURE_PAGE" => "structure.php",
		"G_BIRTHDAY_PM_URL" => "/company/personal/messages/chat/#USER_ID#/",
		"G_BIRTHDAY_SHOW_YEAR" => "M",
		"G_BIRTHDAY_USER_PROPERTY" => array(
			0 => "PERSONAL_PHONE",
			1 => "PERSONAL_MOBILE",
			2 => "UF_DEPARTMENT",
			3 => "",
		),
		"G_BIRTHDAY_LIST_URL" => "/company/birthdays.php",
		"G_LIFE_IBLOCK_TYPE" => "news",
		"G_LIFE_IBLOCK_ID" => "1",
		"G_LIFE_DETAIL_URL" => "/about/life.php?ID=#ELEMENT_ID#",
		"G_LIFE_CACHE_TYPE" => "A",
		"G_LIFE_CACHE_TIME" => "3600",
		"G_LIFE_LIST_URL" => "/about/life.php",
		"G_OFFICIAL_IBLOCK_TYPE" => "news",
		"G_OFFICIAL_IBLOCK_ID" => "2",
		"G_OFFICIAL_DETAIL_URL" => "/about/official.php?ID=#ELEMENT_ID#",
		"G_OFFICIAL_CACHE_TYPE" => "A",
		"G_OFFICIAL_CACHE_TIME" => "3600",
		"G_OFFICIAL_LIST_URL" => "/about/",
		"G_SHARED_DOCS_IBLOCK_TYPE" => "library",
		"G_SHARED_DOCS_IBLOCK_ID" => "22",
		"G_SHARED_DOCS_DETAIL_URL" => "/docs/shared/element/view/#ELEMENT_ID#/",
		"G_SHARED_DOCS_CACHE_TYPE" => "A",
		"G_SHARED_DOCS_CACHE_TIME" => "3600",
		"G_SHARED_DOCS_LIST_URL" => "/docs/",
		"G_COMPANY_CALENDAR_IBLOCK_TYPE" => "events",
		"G_COMPANY_CALENDAR_IBLOCK_ID" => "14",
		"G_COMPANY_CALENDAR_DETAIL_URL" => "/about/calendar.php",
		"G_COMPANY_CALENDAR_CACHE_TIME" => "3600000",
		"G_PHOTOS_IBLOCK_TYPE" => "photos",
		"G_PHOTOS_IBLOCK_ID" => "23",
		"G_PHOTOS_DETAIL_URL" => "/about/gallery/#SECTION_ID#/#ELEMENT_ID#/",
		"G_PHOTOS_DETAIL_SLIDE_SHOW_URL" => "/about/gallery/#SECTION_ID#/#ELEMENT_ID#/slide_show/",
		"G_PHOTOS_CACHE_TYPE" => "A",
		"G_PHOTOS_CACHE_TIME" => "3600000",
		"G_PHOTOS_LIST_URL" => "/about/gallery/",
		"G_WORKGROUPS_GROUP_VAR" => "group_id",
		"G_WORKGROUPS_PATH_TO_GROUP" => "/workgroups/group/#group_id#/",
		"G_WORKGROUPS_PATH_TO_GROUP_SEARCH" => "/workgroups/",
		"G_WORKGROUPS_CACHE_TIME" => "180",
		"G_BLOG_PATH_TO_BLOG" => "/company/personal/user/#user_id#/blog/",
		"G_BLOG_PATH_TO_POST" => "/company/personal/user/#user_id#/blog/#post_id#/",
		"G_BLOG_PATH_TO_GROUP_BLOG_POST" => "/workgroups/group/#group_id#/blog/#post_id#/",
		"G_BLOG_PATH_TO_USER" => "/company/personal/user/#user_id#/",
		"G_BLOG_CACHE_TYPE" => "A",
		"G_BLOG_CACHE_TIME" => "180",
		"G_FORUM_FID" => array(
			0 => "1",
		),
		"G_FORUM_SORT_BY" => "LAST_POST_DATE",
		"G_FORUM_SORT_ORDER" => "DESC",
		"G_FORUM_URL_TEMPLATES_MESSAGE" => "/community/forum/messages/forum#FID#/topic#TID#/message#MID#/",
		"G_FORUM_CACHE_TYPE" => "A",
		"G_FORUM_CACHE_TIME" => "180",
		"G_TASKS_IBLOCK_ID" => "26",
		"G_TASKS_PATH_TO_GROUP_TASKS" => "/workgroups/group/#group_id#/tasks/",
		"G_TASKS_PATH_TO_GROUP_TASKS_TASK" => "/workgroups/group/#group_id#/tasks/task/#action#/#task_id#/",
		"G_TASKS_PATH_TO_USER_TASKS" => "/company/personal/user/#user_id#/tasks/",
		"G_TASKS_PATH_TO_USER_TASKS_TASK" => "/company/personal/user/#user_id#/tasks/task/#action#/#task_id#/",
		"G_CALENDAR_IBLOCK_TYPE" => "events",
		"G_CALENDAR_IBLOCK_ID" => "16",
		"G_CALENDAR_DETAIL_URL" => "/company/personal/user/#user_id#/calendar/",
		"G_CALENDAR_CACHE_TYPE" => "N",
		"G_CALENDAR_CACHE_TIME" => "3600000",
		"G_HONOUR_LIST_URL" => "/company/leaders.php",
		"G_NEW_EMPLOYEES_LIST_URL" => "/company/events.php",
		"COMPONENT_TEMPLATE" => ".default",
		"PM_URL" => "/company/personal/messages/chat/#USER_ID#/",
		"PATH_TO_CONPANY_DEPARTMENT" => "/company/structure.php?set_filter_structure=Y&structure_UF_DEPARTMENT=#ID#",
		"NAME_TEMPLATE" => "",
		"SHOW_LOGIN" => "Y",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"DATE_FORMAT" => "d.m.Y",
		"DATE_FORMAT_NO_YEAR" => "d.m",
		"SHOW_YEAR" => "M",
		"GADGETS_FIXED" => array(
			0 => "PHOTOS",
		),
		"GU_VIDEO_TITLE_STD" => "",
		"GU_CRM_CONTACT_LIST_TITLE_STD" => "",
		"GU_CRM_CONTACT_LIST_TYPE_ID" => "",
		"GU_CRM_CONTACT_LIST_ONLY_MY" => "N",
		"GU_CRM_CONTACT_LIST_SORT" => "DATE_CREATE",
		"GU_CRM_CONTACT_LIST_SORT_BY" => "DESC",
		"GU_CRM_CONTACT_LIST_CONTACT_COUNT" => "5",
		"G_HELLO_TEXT_MSG" => "Привет, #NAME#! Мы виделись #CNT# раз.",
		"GU_HELLO_TITLE_STD" => "",
		"GU_HELLO_TEXT_NAME" => "друг"
	),
	false
);

?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>